<section
	class="cloudflare ssl_tls authenticated_origin_pulls initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="ssl_tls"
	data-section-name="authenticated_origin_pulls" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Authenticated Origin Pulls</span>
			<p>TLS client certificate presented for authentication on origin pull.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>Authenticated Origin Pulls</h4>
			<p><a target="blank" href="https://origin-pull.cloudflare.com/">Authenticated Origin Pulls</a> allow you to cryptographically verify that requests to your origin server have come from Cloudflare using a TLS client certificate. This prevents clients from sending requests directly to your origin, bypassing security measures provided by Cloudflare, such as IP and Web Application Firewalls, logging, and encryption.<br>This feature requires additional configuration at your web server. Instructions are available for <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/225006628">Apache</a> and <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/204494148">nginx</a>.</p>
			<br>
			<h5>Additional Resources</h5>
			<p><a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/204899617-Authenticated-Origin-Pulls">Authenticated Origin Pulls</a></p>
		</div>
	</div>
</section>
