<section
	class="cloudflare ssl_tls certificate_transparency_monitoring initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="ssl_tls"
	data-section-name="certificate_transparency_monitoring" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Certificate Transparency Monitoring</span>
			<p>Receive an email when a Certificate Authority issues a certificate for your domain.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is Certificate Transparency Monitoring?</h4>
			<p>Every day, millions of certificates are issued for domains. Each certificate is recorded in a set of public logs for transparency. With Certificate Transparency Monitoring, we crawl these logs and send you an email when we find a certificate for your domain. If you manage example.com, we'll catch *.example.com to help you spot malicious or unexpected certificates.</p>
			<h4>Why should I enable Certificate Transparency Monitoring?</h4>
			<p>In rare cases, attackers will obtain certificates for websites they do not own. If an attacker gets a certificate for your website, they can serve content on your behalf that looks legitimate but is actually malicious. Some customers also lose track of certificates and like to be notified when new ones are issued. We encourage all customers to enable monitoring and look for suspicious activity.</p>
			<h4>Who will receive these email alerts?</h4>
			<p>If you're on a Free or Pro account and have enabled this feature, we will send alerts to your Cloudflare account email address (and those with Shared Account Access). If you're on a Business or Enterprise account, we will only send alerts to the emails you specifically enroll above.</p>
			<h4>What should I do if I find a malicious certificate?</h4>
			<p>We have created a detailed article to help in this situation. It can be found <a href="https://support.cloudflare.com/hc/articles/360031379012" >here</a>.</p>
		</div>
	</div>
</section>
