<section
	class="cloudflare ssl_tls ssl_tls_recommender initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="ssl_tls"
	data-section-name="ssl_tls_recommender" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >SSL/TLS Recommender</span>
			<p>To check if your website can use a more secure SSL/TLS mode, enable the SSL/TLS Recommender. Receive an email with Cloudflare’s recommendation.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>About SSL/TLS Recommender</h4>
			<p>After enabling the SSL/TLS Recommender, the zone owner will receive an email if a recommendation for a more secure SSL/TLS mode is available. If no email is received, the recommendation is to keep the current mode. You are not required to use the recommendation. The Recommender runs periodically and sends notifications if new recommendations become available. The recommendation is never lower than your current SSL/TLS mode.</p>
			<p>The SSL/TLS Recommender is not intended to resolve issues with website or domain functionality. If your website is not functional at its current mode, no recommendation will be provided. <a href="https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options" target="_blank" >Learn more</a>.</p>
		</div>
	</div>
</section>
