<section
	class="cloudflare dns cloudflare_nameservers initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="dns"
	data-section-name="cloudflare_nameservers" >
	<div class="row" >
		<div class="wrapper_left holds_table" >
			<span class="section_title" >Cloudflare Nameservers</span>
			<p>To use Cloudflare, you need to change your domain's authoritative DNS servers, which are also referred to as nameservers. For your reference, here are the Cloudflare nameservers you've been assigned.</p>
			<table cellpadding="0" cellspacing="0" data-image-base="<?php echo $block->getSkinUrl ('images/cloudflare') ?>" >
				<tr>
					<th>Type</th>
					<th>Value</th>
				</tr>
				<tr>
					<td colspan="2" >No DNS records found.</td>
				</tr>
			</table>
		</div>
		<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" > </div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>How do I change my nameservers?</h4>
			<p>Login to your registrar to change your nameservers. You can find step by step instructions on how to change nameservers for the most common registrars on our <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/205195708-Step-3-Change-your-domain-name-servers-to-Cloudflare">knowledge base</a>.</p>
			<h4>Are two nameservers enough?</h4>
			<p>Yes. At Cloudflare, the two nameservers reference clusters of servers in each of our <a target="blank" href="https://www.cloudflare.com/network/">datacenters</a> worldwide, allowing for greater speed and resiliency.</p>
			<p><strong>Note:</strong> Only the two Cloudflare nameservers can be used. All other nameservers must be removed otherwise Cloudflare will not work.</p>
		</div>
	</div>
</section>
