<section
	class="cloudflare dns custom_nameservers initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="dns"
	data-section-name="custom_nameservers" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Custom Nameservers</span>
			<p>Custom nameservers allow you to create your own, unique nameservers in place of your assigned Cloudflare nameservers. To switch to using custom nameservers, first create them here, then add them as glue records at your registrar.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<input id="action" class="trigger" type="button" value="Add custom nameservers" data-target="edit" />
			</div>
		</div>
	</div>
	<div class="row" >
		<table class="nameservers" cellpadding="0" cellspacing="0" >
			<thead>
				<tr>
					<th>Nameserver</th>
					<th>IPv4 Address</th>
					<th>IPv6 Address</th>
				</tr>
			</thead>
			<tbody></tbody>
		</table>
	</div>
	<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is a custom nameserver?</h4>
			<p>Cloudflare enables you to use nameservers which reflect your own domain (eg. ns.example.com). You can use them in place of your Cloudflare assigned nameservers.</p>
			<p>Custom nameservers have the following limitations:</p>
			<ul>
				<li>You must have between two and five custom nameservers</li>
				<li>The custom nameservers can only be created as subdomains of example.com (e.g. ns1.example.com and ns2.example.com).</li>
				<li>When custom nameservers are created, glue records need to be created at your registrar with the IP addresses of your custom nameservers. Failure to do so can cause all DNS lookups for your site to fail. Further information can be found here: <a href="https://support.cloudflare.com/hc/articles/200169006" >Can I get vanity or custom nameservers using Cloudflare?</a></li>
			</ul>
			<p><strong>Note:</strong> Your assigned Cloudflare nameservers will continue to work even after custom nameservers are enabled.</p>
		</div>
	</div>
</section>
