<section
	class="cloudflare dns cname_flattening initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="dns"
	data-section-name="cname_flattening" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >CNAME Flattening</span>
			<p>Cloudflare will follow a CNAME to where it points and return that IP address instead of the CNAME record. By default, Cloudflare will only flatten the CNAME at the root of your domain.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<select class="trigger-select" name="value" data-target="update" >
					<option value="flatten_at_root" >Flatten CNAME at root</option>
					<option value="flatten_all" >Flatten all CNAMEs</option>
				</select>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is CNAME Flattening?</h4>
			<p>With CNAME Flattening, Cloudflare will follow a CNAME to where it points and return that IP address instead of the CNAME record itself.</p>
			<p>There are two main benefits:</p>
			<ul>
				<li>CNAME flattening allows Cloudflare website owners to add CNAMEs at the root of the domain, which is otherwise not allowed in the DNS specification.</li>
				<li>CNAME flattening speeds up DNS resolution on CNAMEs by up to 30%.</li>
			</ul>
			<p>You can learn more about CNAME flattening <a href="https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/" >on our blog</a>.</p>
		</div>
	</div>
</section>
