<section
	class="cloudflare overview configuration"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="overview"
	data-section-name="configuration" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Configuration</span>
			<p>Credentials, such as your Cloudflare email address and Cloudflare API token, are used to communicate with the Cloudflare API. The API token is not displayed for security reasons.  Please see the <i>Credential Validation</i> section below to see if valid credentials are currently saved for your Cloudflare account.</p>
			<div class="status_pair" >
				<label>Credential Validation:</label>
				<p><?php echo $block->getValidationState () ?></p>
			</div>
			<div class="status_pair" >
				<label>Zone ID:</label>
				<p><?php echo empty ( $block->getZoneId () ) ? "Unrecognized Site" : $block->getZoneId () ?></p>
			</div>
		</div>
		<div class="wrapper_right" >
			<div>
				<form method="POST" action="<?php echo $block->getUrl ("cloudflare/dashboard/save") ?>" >
					<input name="form_key" type="hidden" value="<?php echo $block->getFormKey () ?>" />
					<input name="zone" type="text" placeholder="Zone ID" value="<?php echo $block->getAuthZone () ?>" />
					<input name="token" type="password" placeholder="API Token" autocomplete="nope" autofill="off" />
					<input class="full" type="submit" value="Save Credentials" />
				</form>
			</div>
		</div>
	</div>
	<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" > </div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h3>User Manual</h3>
			<p>In order for this module to work, access to Cloudflare's API must be configured. Please refer to this extensions user manual for information about the set up process. The user manual can be found <a href="https://learn.jetrails.com/article/magento-2-cloudflare-extension" target="_blank" >here</a>.</p>
		</div>
	</div>
</section>
