<section
	class="cloudflare overview status initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="overview"
	data-section-name="status" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Pause Website</span>
			<p>Pause will temporarily deactivate Cloudflare for your domain. Cloudflare will continue to resolve DNS for your website, but all requests will go directly to your origin which means you will not receive performance and security benefits. All of your settings will be saved.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<input class="trigger" data-target="resume" type="button" value="Pause" />
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" > </div>
		</div>
	</div>
</section>
