<section
	class="cloudflare network grpc initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="grpc" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >gRPC</span>
			<p>Allow gRPC connections to your origin server. <a href="https://support.cloudflare.com/hc/articles/360050483011">Learn more</a>.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<p>gRPC is a protocol designed to build high-performance APIs. Toggling gRPC allows you to orange-cloud API endpoints and allow gRPC traffic to flow through Cloudflare. <a href="https://support.cloudflare.com/hc/articles/360050483011">More information</a>.</p>
		</div>
	</div>
</section>
