<section
	class="cloudflare network http_2_to_origin initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="http_2_to_origin" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >HTTP/2 to Origin</span>
			<p>Allow HTTP/2 requests between Cloudflare's edge and your origin</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<p><a href="https://developers.cloudflare.com/cache/how-to/enable-http2-to-origin">Developer documentation</a></p>
		</div>
	</div>
</section>
