<section
	class="cloudflare network ip_geolocation initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="ip_geolocation" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >IP Geolocation</span>
			<p>Include the country code of the visitor location with all requests to your website.</p>
			<p><strong>Note:</strong> You must retrieve the IP Geolocation information from the CF-IPCountry HTTP header.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is IP Geolocation?</h4>
			<p>Cloudflare can geolocate visitors to your website and pass the country code on to you. Once enabled, we will then add an HTTP header named “CF-IPCountry” to all requests we make to your website.</p>
			<p><strong>Note:</strong> Cloudflare uses a GeoIP database to map IP address to countries. “XX” means that there wasn’t a record for in our geolocation database for an IP address.</p>
			<p><a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168236-What-does-Cloudflare-IP-Geolocation-do" >What does enabling Cloudflare IP Geolocation do?.</a></p>
			<br>
			<h5>Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-">How does Cloudflare handle HTTP Request headers?</a>
			<br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168236-What-does-Cloudflare-IP-Geolocation-do" >What does Cloudflare IP Geolocation do?</a>
		</div>
	</div>
</section>
