<section
	class="cloudflare network ipv6_compatibility initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="ipv6_compatibility" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >IPv6 Compatibility</span>
			<p>Enable IPv6 support and gateway.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is IPv6?</h4>
			<p>As the Internet runs low on IPv4 address space, there’s been a rapid increase in the deployment of IPv6 technologies. This shift is critical to the long-term growth and health of the Internet. At Cloudflare, we are <a target="blank" href="https://www.cloudflare.com/ipv6">doing our part</a> to make it free and easy for all websites to be available on network.ipv6.</p>
			<h4>What does enabling IPv6 compatibility do?</h4>
			<p>The IPv6 gateway setting enables IPv6 on all subdomains that are on Cloudflare (marked by an orange cloud in your DNS settings). If your host provides IPv6 support, the gateway will proxy IPv6 connections through Cloudflare. We recommend keeping IPv6 Compatibility set to “On” for greater availability for your website.</p>
			<p><strong>Note:</strong> If you already have IPv6 records on your origin server, you must enable Cloudflare for your AAAA records on the DNS settings page.</p>
			<h4>Why can’t I turn off IPv6?</h4>
			<p>At Cloudflare we believe in being good to the Internet and good to our customers. By moving on from the legacy world of IPv4-only to the modern-day world where IPv4 and IPv6 are treated equally, we believe we are doing exactly that. In the Cloudflare dashboard, IPv6 is no longer something you can toggle on and off, it’s always just on. However, if you need to turn off IPv6 (and say goodbye to the modern internet), you may still do so <a target="blank" href="https://api.cloudflare.com/#zone-settings-change-ipv6-setting" >using the Cloudflare API</a>.</p>
			<br>
			<h5>Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168806-I-activated-through-a-hosting-partner-Can-I-still-use-the-free-Cloudflare-IPv6-Compatibility-">I activated through a hosting partner. Can I still use the free Cloudflare IPv6 Compatibility?</a>
			<br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168586-What-does-the-IPv6-Compatibility-option-mean" >What does the IPv6 Compatibility option mean?</a>
		</div>
	</div>
</section>
