<section
	class="cloudflare network onion_routing initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="onion_routing" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Onion Routing</span>
			<p>Onion Routing allows routing traffic from legitimate users on the Tor network through Cloudflare’s onion services rather than exit nodes, thereby improving privacy of the users and enabling more fine-grained protection.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>How does Onion Routing work?</h4>
			<p>When this setting is enabled, the response to HTTPS requests coming from the Tor Browser will include an "alt-svc" header containing the address of one or more onion services operated by us. The Tor Browser establishes a Tor circuit with one of our onion services and, after a verification step by the browser, the subsequent requests will be routed through the onion service instead.<br>This allows us to distinguish individual circuits and only challenge circuits that show unusual behavior, while keeping users’ anonymity intact.</p>
		</div>
	</div>
</section>
