<section
	class="cloudflare network pseudo_ipv4 initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="pseudo_ipv4" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Pseudo IPv4</span>
			<p>Adds an IPv4 header to requests when a client is using IPv6, but the server only supports IPv4.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<select class="trigger-select" name="value" data-target="update" >
					<option value="off" >Off</option>
					<option value="add_header" >Add Header</option>
					<option value="overwrite_header" >Overwrite Headers</option>
				</select>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is Pseudo IPv4?</h4>
			<p>As a stopgap to accelerate the adoption of IPv6, Cloudflare offers Pseudo IPv4 which supports IPv6 addresses in legacy applications expecting IPv4 addresses. The goal is to provide a nearly unique IPv4 address for each IPv6 address, using Class E IPv4 address space, which is designated as experimental and would not normally see traffic. To learn more see <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/202494830-Pseudo-IPv4-Supporting-IPv6-addresses-in-legacy-IPv4-applications" >here</a>.</p>
			<h4>Options</h4>
			<ul>
				<li><strong>Add header:</strong> Add additional Cf-Pseudo-IPv4 header only</li>
				<li><strong>Overwrite headers:</strong> Overwrite the existing Cf-Connecting-IP and X-Forwarded-For headers with a pseudo IPv4 address.</li>
			</ul>
			<p><strong>Note:</strong> We recommend leaving this set to “Off” unless you have a specific need.</p>
		</div>
	</div>
</section>
