<section
	class="cloudflare network response_buffering initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="response_buffering" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Response Buffering</span>
			<p>Enable or disable buffering of responses from the origin server.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What does Response Buffering do?</h4>
			<p>By default, Cloudflare sends packets to the client as we receive them. Enabling Response Buffering means that Cloudflare will wait until it has the entire file before forwarding it to the end user.</p>
			<p>Use Response Buffering if you would prefer Cloudflare deliver a full payload all at once to the client.</p>
			<p><a href="https://support.cloudflare.com/hc/en-us/articles/206049798-What-is-Response-Buffering" >What is response buffering?</a></p>
		</div>
	</div>
</section>
