<section
	class="cloudflare network websockets initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="websockets" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >WebSockets</span>
			<p>Allow WebSockets connections to your origin server. Concurrent connection guidelines for your plan: Low. <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200169466-Can-I-use-Cloudflare-with-WebSockets" >Learn More</a>.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What are WebSockets?</h4>
			<p>WebSockets are open connections sustained between the client and the origin server. Inside a WebSockets connection, the client and the origin can pass data back and forth without having to reestablish sessions. This makes exchanging data within a WebSockets connection fast. WebSockets are often used for real-time applications such as live chat and gaming.</p>
			<h4>Why use WebSockets?</h4>
			<p>Because WebSockets creates a single connection and doesn’t need multiple HTTP headers, WebSockets can provide anywhere from 500:1 to a 1000:1 reduction in unnecessary HTTP header traffic compared to HTTP polling solutions.</p>
			<p>The server no longer needs to wait for a request to come back before it sends new data; it can simply push the data to the client the moment it has new information. Tests have shown a 3:1 reduction in latency compared to polling solutions.</p>
			<p>For more technical information on the WebSockets, you can read up on the <a target="blank" href="https://html.spec.whatwg.org/multipage/comms.html#network" >HTML5 Web Sockets Specification.</a></p>
			<h4>How can I use WebSockets with Cloudflare?</h4>
			<p>No additional configuration is required to send WebSockets traffic through Cloudflare. Cloudflare will immediately begin proxying your WebSockets through to your origin.</p>
			<h4>Can I use WebSockets over SSL?</h4>
			<p>Yes. WebSockets through Cloudflare are fully compatible with Cloudflare’s SSL.</p>
			<p>For more information on WebSockets, see <a target="blank" href="https://www.cloudflare.com/website-optimization/web-sockets/">here.</a></p>
		</div>
	</div>
</section>
