<section
	class="cloudflare network http_2 initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="http_2" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >0-RTT Connection Resumption</span>
			<p>Improves performance for clients who have previously connected to your website.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is 0-RTT Connection Resumption?</h4>
			<p>0-RTT Connection Resumption allows the client’s first request to be sent before the TLS or QUIC connection is fully established, resulting in faster connection times, when the client is resuming a connection that was previously already established.</p>
		</div>
	</div>
</section>
