<section
	class="cloudflare caching argo_tiered_cache initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="caching"
	data-section-name="argo_tiered_cache" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Argo Tiered Cache</span>
			<p>Argo is a service that uses optimized routes across the Cloudflare network to <strong>deliver responses to your users more quickly, reliably, and securely.</strong></p>
			<p>Tiered caching is a practice where Cloudflare's network of global data centers are divided into a hierarchy of upper-tiers and lower-tiers. In order to control bandwidth and number of connections between an origin and Cloudflare, only upper-tiers are permitted to request content from an origin and are responsible for distributing information to the lower-tiers.</p>
			<p>By enabling Tiered Cache, Cloudflare will dynamically find the single best upper tier for an origin using Argo performance and routing data.</p>
			<p>This practice improves bandwidth efficiency by limiting the number of data centers that can ask the origin for content, reduces origin load, and makes websites more cost-effective to operate.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<p><strong>Tiered Caching</strong></p>
			<p>Argo's tiered caching technology uses regional tier 1 Cloudflare data centers to propagate content to Cloudflare's global network, minimizing static content requests to your server, while reducing bandwidth and total costs.</p>
		</div>
	</div>
</section>
