<section
	class="cloudflare caching crawler_hints initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="caching"
	data-section-name="crawler_hints" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Crawler Hints</span>
			<p>Crawler Hints provide high quality data to search engines and other crawlers when sites using Cloudflare change their content. This allows crawlers to precisely time crawling, avoid wasteful crawls, and generally reduce resource consumption on origins and other Internet infrastructure.</p>
			<p>By enabling this service, you agree to share website information required for feature functionality and agree to the <a href="https://www.cloudflare.com/supplemental-terms/#crawler-hints">Supplemental Terms</a> for Crawler Hints.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4 id="how-does-crawler-hints-work-">How does Crawler Hints work?</h4>
			<p>When enabled, Cloudflare pushes signals to networks that operate large crawling operations, such as search engines, when we believe content on your website has changed and needs to be re-indexed.</p>
			<p>Search engines crawl your website depending on algorithms that differ based on provider. Often, the cadence search engines crawl your site is based on either a regular interval or data about past website updates, and these factors may not be aligned with real world content changes. This crawling approach may not only harm customer page rank, but also works to the detriment of a search engine’s operational costs and environmental impact. The goal of Crawler Hints is to help search indexers make a more informed decision on when content has changed to make the Internet greener and more energy efficient.</p>
			<p><a href="https://blog.cloudflare.com/crawler-hints-how-cloudflare-is-reducing-the-environmental-impact-of-web-searches/">Crawler Hints: How Cloudflare Is Reducing The Environmental Impact Of Web Searches</a></p>
		</div>
	</div>
</section>