<section class='tabs-wrapper at_least_one' >
	<div data-tab='configuration' class="active" >Configuration</div>
	<div data-tab-content='configuration' class='active' >
		<?php

			echo $block->renderSections ( "caching/configuration_tab", array (
				"purge_cache",
				"caching_level",
				"browser_cache_expiration",
				"always_online",
				"development_mode",
				"enable_query_string_sort"
			));

		?>
	</div>
</section>
