<section class='tabs-wrapper at_least_one' >
	<div data-tab='managed_rules' class="active" >Managed Rules</div>
	<div data-tab='tools' >Tools</div>
	<div data-tab='settings' >Settings</div>
	<div data-tab-content='managed_rules' class='active' >
		<?php

			echo $block->renderSections ( "firewall/managed_rules_tab", array (
				"web_application_firewall"
			));

		?>
	</div>
	<div data-tab-content='tools' >
		<?php

			echo $block->renderSections ( "firewall/tools_tab", array (
				"access_rules",
				"user_agent_blocking",
				"unmetered_ddos_mitigation"
			));

		?>
	</div>
	<div data-tab-content='settings' >
		<?php

			echo $block->renderSections ( "firewall/settings_tab", array (
				"security_level",
				"bot_fight_mode",
				"bot_management",
				"javascript_detections",
				"challenge_passage",
				"browser_integrity_check",
				"privacy_pass_support"
			));

		?>
	</div>
</section>
