<h1 class="tab-content" >SSL/TLS</h1>
<h2 class="tab-content" >Manage cryptography settings for your website</h2>
<?php

	echo $block->renderSections ( "ssl_tls", array (
		"ssl",
		"always_use_https",
		"http_strict_transport_security",
		"authenticated_origin_pulls",
		"opportunistic_encryption",
		"minimum_tls_version",
		"onion_routing",
		"tls_13",
		"automatic_https_rewrites",
		"disable_universal_ssl"
	));

?>
