<section class='tabs-wrapper at_least_one' >
	<div data-tab='overview' class="active" >Overview</div>
	<div data-tab='edge_certificates' >Edge Certificates</div>
	<div data-tab='origin_server' >Origin Server</div>
	<div data-tab-content='overview' class='active' >
		<?php

			echo $block->renderSections ( "ssl_tls/overview_tab", array (
				"ssl",
				"ssl_tls_recommender"
			));

		?>
	</div>
	<div data-tab-content='edge_certificates' >
		<?php

			echo $block->renderSections ( "ssl_tls/edge_certificates_tab", array (
				"always_use_https",
				"http_strict_transport_security",
				"minimum_tls_version",
				"opportunistic_encryption",
				"tls_13",
				"automatic_https_rewrites",
				"certificate_transparency_monitoring",
				"disable_universal_ssl"
			));

		?>
	</div>
	<div data-tab-content='origin_server' >
		<?php

			echo $block->renderSections ( "ssl_tls/origin_server_tab", array (
				"authenticated_origin_pulls"
			));

		?>
	</div>
</section>
