<section
	class="cloudflare ssl_tls tls_13 initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="ssl_tls"
	data-section-name="tls_13" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >TLS 1.3</span>
			<p>Enable the latest version of the TLS protocol for improved security and performance.</p>
		</div>
		<div class="wrapper_right" >
			<div class="group_wrapper full" >
				<select name="value" data-target="update" class="trigger-select selection" >
					<option value="off" >Disabled</option>
					<option value="on" >Enabled</option>
					<option value="zrt" >Enabled+0RTT</option>
				</select>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is TLS 1.3?</h4>
			<p>TLS 1.3 is the newest, fastest, and most secure version of the TLS protocol. SSL/TLS is the protocol that encrypts communication between users and your website. When web traffic is encrypted with TLS, users will see the green padlock in their browser window. By turning on the TLS 1.3 feature, traffic to and from your website will be served over the TLS 1.3 protocol when supported by clients.</p>
			<h4>What is 0-RTT?</h4>
			<p>0-RTT is a feature that improves performance for clients who have previously connected to your website. It allows the client’s first request to be sent before the TLS connection is fully established, resulting in faster connection times.</p>
			<p>Note: TLS 1.3 is a beta feature. We do not guarantee every TLS 1.3-capable request will be served over TLS 1.3.</p>
		</div>
	</div>
</section>
