<section
	class="cloudflare speed amp_real_url initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="amp_real_url" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >AMP Real URL</span>
			<p>Display your site's actual URL on your AMP pages, instead of the traditional Google AMP cache URL.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h3>What does AMP Real URL do?</h3>
			<p>Traditionally, clicking on a search result for an AMP page takes visitors to a cached page served from google.com/amp/. AMP Real URL allows mobile browsers to show your site's actual URL while still serving the content from Google's AMP cache. This is accomplished through cryptographic signed exchanges. AMP Real URL only works on pages that are compatible with the AMP specification and only applies to visitors coming from Chrome on Android at this time. As the underlying technology gets adopted by more browsers, more visitors to your site will be able to view your real URL.</p>
			<p>Showing the actual URL offers several advantages:</p>
			<ul>
				<li>Brand fidelity - Site visitors see your brand, not Google's, at the top of all your pages.</li>
				<li>More accurate analytics - Keeping AMP and non-AMP content in the same domain facilitates more accurate analytics attribution.</li>
				<li>Reduced bounce rates - Showing your actual URL may encourage users to remain on your site, instead of returning to the search results page.</li>
				<li>Security - AMP Real URL uses cryptography to sign your AMP pages with a publicly verifiable certificate, ensuring no one can add, remove, or modify your content.</li>
			</ul>
			<h3>How do I see it working?</h3>
			<p>After the feature is enabled, it takes the Google AMP Cache about a week to detect and serve the new URL. Simply visit your AMP pages from Google search results from Android Chrome and you should be able to see your actual URL. You can also go to https://your-domain.com/cdn-fpw/sxg/cert.pem.msg to verify that the feature is working. If the page does not 404 and prompts you to download a certificate, then you're all set!</p>
		</div>
	</div>
</section>
