<section
	class="cloudflare speed automatic_platform_optimization initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="automatic_platform_optimization" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Automatic Platform Optimization for WordPress</span>
			<p>Improve the performance of your WordPress site. Automatic Platform Optimization for WordPress serves your WordPress site from Cloudflare's edge network and caches third party fonts. Get the benefits of a static site without any changes to how you manage your site. This results in consistent, fast TTFB and content loading faster.</p>
			<p>Learn more in our <a href="https://blog.cloudflare.com/automatic-platform-optimizations-starting-with-wordpress/" >announcement blog post for APO</a>.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<div class="group_wrapper" style="text-align: center" >
					<label class="switch" >
						<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
						<span class="knob" ></span>
					</label>
				</div>
				<div class="group_wrapper" style="max-width: 200px" >
					<input class="full" type="button" value="Install WordPress Plugin" onClick="window.open ( 'https://wordpress.org/plugins/cloudflare/', '_blank' )" />
				</div>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<p>For more information about how APO provides better performance to your WordPress site, see <a href="https://support.cloudflare.com/hc/en-us/articles/360049822312" >this support article</a>.</p>
		</div>
	</div>
</section>
