<section
	class="cloudflare speed auto_minify initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="auto_minify" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Auto Minify</span>
			<p>Reduce the file size of source code on your website.</p>
			<p><b>Note:</b> Purge cache to have your change take effect immediately.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<div class="group_wrapper" >
					<input class="trigger" data-target="change" id="javascript" value="javascript" type="checkbox" />
					<label for="javascript" >JavaScript</label>
				</div>
				<div class="group_wrapper" >
					<input class="trigger" data-target="change" id="css" value="css" type="checkbox" />
					<label for="css" >CSS</label>
				</div>
				<div class="group_wrapper" >
					<input class="trigger" data-target="change" id="html" value="html" type="checkbox" />
					<label for="html" >HTML</label>
				</div>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" > </div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What does Auto Minify do?</h4>
			<p>Auto Minify removes unnecessary characters from your source code (like whitespace, comments, etc.) without changing its functionality.</p>
			<p>Minification can compress source file size which reduces the amount of data that needs to be transferred to visitors and thus improves page load times.</p>
			<h4>Why isn’t Auto Minify working?</h4>
			<p>Cloudflare’s Auto Minify feature may intentionally not minify some scripts under specific circumstances to ensure we don’t create errors in your website code. On these occasions the code will be delivered unminified:</p>
			<ul>
				<li>If the file is served from an external service or a domain not powered by Cloudflare  (For example Google, Facebook, Twitter, widgets etc). For more, take a look at <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168066-Does-Auto-Minify-impact-third-party-script">Does Auto Minify impact third party scripts?</a></li>
				<li>If the file contains .min in the filename</li>
				<li>If the file has syntax errors and it cannot be parsed</li>
				<li>Inline CSS or JS embedded inside your HTML code will not be minified</li>
				<li>Auto Minify will not remove newlines from your HTML but will remove unnecessary whitespace</li>
			</ul>
			<p>For more read the full article <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200169876-Why-isn-t-Auto-Minify-working">Why isn’t Auto Minify working?</a></p>
			<br>
			<h5>Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200169876-Why-isn-t-Auto-Minify-working">Why isn't Auto Minify working?</a>
			<br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168066-Does-Auto-Minify-impact-third-party-script">Does Auto Minify impact third-party script?</a>
		</div>
	</div>
</section>
