<section
	class="cloudflare speed mirage initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="mirage" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Mirage</span>
			<p>Improve load time for pages that include images on mobile devices with slow network connections.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What does Mirage do?</h4>
			<p><a target="blank" href="https://www.cloudflare.com/mirage" >Mirage tailors image loading</a> based on network connection and device type. Devices with small screens receive smaller images, and slower connections receive lower resolution images. This speeds up page rendering so users can begin interacting with your website without waiting for images to download first.</p>
			<p>Mirage improves page load time by:</p>
			<ul>
				<li><p><strong>Image Virtualizing:</strong> Replaces images with low resolution placeholder images that have the same dimensions as the original (including third party images). Once the page renders completely, full resolution images are then lazy-loaded (prioritizing images in the browser viewport). This process allows pages to render quickly and minimizes browser reflow.</p></li>
				<li><p><strong>Request Streamlining:</strong> Combines multiple individual network requests for images into a single request.</p></li>
			</ul>
			<p><strong>Note:</strong> Mirage does not transcode or otherwise alter the original full-resolution images.</p>
			<p><em>Mirage is considered <strong>Beta</strong> because it’s an experimental feature that may cause issues displaying images in association with certain Javascript libraries, such as image carousels or photo viewers. Issues with Mirage affect only a small percentage of customers.</em></p>
			<br>
			<h5>Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/219178057-Mirage" >Mirage</a><br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200403554-What-Does-Mirage-Do" >What Does Mirage Do?</a><br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168036-Will-Mirage-and-Polish-optimize-off-site-resources" >Will Mirage and Polish optimize off-site resources?</a><br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168176-What-image-formats-do-Polish-and-Mirage-work-with" >What image formats do Polish and Mirage work with?</a>
		</div>
	</div>
</section>
