<section
	class="cloudflare speed polish initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="polish" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Polish</span>
			<p>Improve image load time by optimizing images hosted on your domain. Optionally, the WebP image codec can be used with supported clients for additional performance benefits.</p>
			<p><b>Note:</b> Purge cache to have your change take effect immediately.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<div class="group_wrapper" >
					<select class="trigger-select" data-target="change" name="value" >
						<option value="off" >Off</option>
						<option value="lossless" >Lossless</option>
						<option value="lossy">Lossy</option>
					</select>
				</div>
				<div class="group_wrapper" style="text-align:center" >
					<input class="trigger" data-target="change" name="webp" value="webp" type="checkbox" />
					<label for="webp" >WebP</label>
				</div>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What does Polish do?</h4>
			<p>Polish reduces image file size by removing metadata (date and time, camera manufacturer and model, etc.), and by compressing images when possible. Smaller file sizes mean faster load times for images and web pages.</p>
			<h4>What Polish setting should I use?</h4>
			<ul>
				<li><strong>Off:</strong> Polish is disabled</li>
				<li><strong>Lossless:</strong> Reduce the size of image files without impacting visual quality
					<ul>
						<li>Remove metadata: PNG, GIF, JPEG</li>
						<li>Lossless compression: GIF, PNG</li>
					</ul>
				</li>
				<li><strong>Lossy:</strong> In addition to the features included in the Basic level, the file size of JPEG images is reduced using lossy compression, which may reduce visual quality
					<ul>
						<li>Lossy compression: JPEG</li>
					</ul>
				</li>
				<li><strong>Serve WebP images:</strong> When the client requesting the image supports the WebP image codec, Cloudflare will serve a WebP version of the image when WebP offers a performance advantage over the original image format.
					<ul>
						<li>Lossy compression: JPEG</li>
						<li>Lossless compression: GIF, PNG<br>Polish <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168176-What-image-formats-do-Polish-and-Mirage-work-with">works with a variety of image formats</a> and is only applied to images hosted on your server.<br><strong>Note:</strong> Large JPEG images are converted to progressive images. Visitors will see an increasingly detailed image as the file is downloaded.</li>
					</ul>
				</li>
			</ul>
			<br>
			<h5>Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200065689-What-does-Polish-do">What does Polish do?</a>
			<br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168036-Will-Mirage-and-Polish-optimize-off-site-resources">Will Mirage and Polish optimize off-site resources?</a>
			<br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168176-What-image-formats-do-Polish-and-Mirage-work-with">What image formats do Polish and Mirage work with?</a>
		</div>
	</div>
</section>
