<section
	class="cloudflare speed tcp_turbo initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="tcp_turbo" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >TCP Turbo</span>
			<p>Reduce latency and throughput with custom-tuned TCP optimizations. Enabled automatically for Pro, Business, and Enterprise customers.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<div class="value" >Disabled</div>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
</section>
