<section
	class="cloudflare network http_2 initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="network"
	data-section-name="http_2" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >HTTP/3 (with QUIC)</span>
			<p>Accelerates HTTP requests by using QUIC, which provides encryption and performance improvements compared to TCP and TLS.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is HTTP/3?</h4>
			<p>HTTP/3 is a major revision of the Web’s protocol designed to take advantage of QUIC, a new encrypted-by-default Internet transport protocol that provides a number of improvements designed to accelerate HTTP traffic as well as make it more secure.</p>
		</div>
	</div>
</section>
