<section
	class="cloudflare firewall challenge_passage initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="firewall"
	data-section-name="challenge_passage" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Challenge Passage</span>
			<p>Specify how long a visitor with a bad IP reputation is allowed access to your website after completing a challenge. After the Challenge Passage TTL expires the visitor in question will have to pass a new Challenge.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<select class="trigger-select" name="value" data-target="update" >
					<option value="300" >5 minutes</option>
					<option value="900" >15 minutes</option>
					<option value="1800" >30 minutes</option>
					<option value="2700" >45 minutes</option>
					<option value="3600" >1 hour</option>
					<option value="7200" >2 hours</option>
					<option value="10800" >3 hours</option>
					<option value="14400" >4 hours</option>
					<option value="28800" >8 hours</option>
					<option value="57600" >16 hours</option>
					<option value="86400" >1 day</option>
					<option value="604800" >1 week</option>
					<option value="2592000" >1 month</option>
					<option value="31536000" >1 year</option>
				</select>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>Why doesn’t the TTL apply to the WAF?</h4>
			<p>Challenge passage does not apply to challenges issued by the Web Application Firewall (WAF) as these challenges are not based on the visitor’s IP address reputation.</p>
		</div>
	</div>
</section>
