<section
	class="cloudflare firewall unmetered_ddos_mitigation"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="firewall"
	data-section-name="unmetered_ddos_mitigation" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Unmetered DDoS Mitigation</span>
			<p>Cloudflare will stand in front of your website regardless of attack size or duration.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				On
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What is a DDoS attack?</h4>
			<p>A Distributed Denial of Service (DDoS) attack uses a cluster of computers to send a large number of requests to a website all at once effectively overloading the website with traffic and taking it offline. To learn more see <a target="blank" href="https://www.cloudflare.com/ddos">here</a>.</p>
			<br>
			<h5>Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200170196-I-am-under-DDoS-attack-what-do-I-do-">I am under DDoS attack, what do I do?</a>
			<br>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200172676-Can-Cloudflare-protect-me-against-DDoS-attacks-">Can Cloudflare protect me against DDoS attacks?</a>
		</div>
	</div>
</section>
