<section
	class="cloudflare scrape_shield email_address_obfuscation initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="scrape_shield"
	data-section-name="email_address_obfuscation" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Email Address Obfuscation</span>
			<p>Obfuscated email addresses displayed on your website to prevent harvesting by bots and spammers, without visible changes to the address for human visitors.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>Why use Email Address Obfuscation?</h4>
			<p>Email harvesters and bots are roaming the Internet looking for email addresses to add to their spam lists. Cloudflare’s Email Address Obfuscation encrypts email addresses on your web pages. This means that email addresses are hidden from harvesters and bots, but still visible to human visitors.</p>
			<p><strong>Note:</strong> Email Address Obfuscation is only applied in certain instances. It will work for email addresses within documents with a MIME type of text/html or application/xhtml+xml. However, it will not work for email addresses inside certain conditional comments, attributes, and tags outlined below.</p>
			<ul>
				<li>
					<strong>All attributes</strong>
				</li>
				<li>
					<strong>Conditional comment:</strong>
					<ul>
						<li><code>&lt;!--email_off--&gt; &lt;!--/email_off--&gt;</code></li>
					</ul>
				</li>
				<li>
					<strong>Tags:</strong>
					<ul>
						<li>script: <code>&lt;script&gt; &lt;/script&gt;</code></li>
						<li>noscript: <code>&lt;noscript&gt; &lt;/noscript&gt;</code></li>
						<li>comments: <code>&lt;!-- --&gt;</code></li>
						<li>textarea: <code>&lt;textarea&gt; &lt;/textarea&gt;</code></li>
						<li>xmp: <code>&lt;xmp&gt; &lt;/xmp&gt;</code></li>
						<li>head: <code>&lt;head&gt; &lt;/head&gt;</code></li>
					</ul>
				</li>
			</ul>
			<br>
			<h5>Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation" >What is Email Address Obfuscation?</a>
		</div>
	</div>
</section>
