<section
	class="cloudflare firewall bot_fight_mode initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="firewall"
	data-section-name="bot_fight_mode" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Bot Fight Mode</span>
			<p>Challenge requests matching patterns of known bots before they can access your site.</p>
			<p>Requests matching Cloudflare-identified, non-legitimate automated traffic patterns will be challenged and/or blocked by Cloudflare.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<p>These challenges may disincentivize automated traffic from accessing your site by requiring the use of additional computational resources.</p>
			<p>Note: Defeating Bots may affect some actions on your website and/or non-automated traffic. For example, it may block access to your APIs and prevent access from mobile applications.</p>
		</div>
	</div>
</section>
