<section
	class="cloudflare firewall bot_management initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="firewall"
	data-section-name="bot_management" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Bot Management</span>
			<p>Automatically enables custom firewall rules and the __cf_bm cookie on your zone to manage incoming traffic that matches criteria associated with bots.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<p>If you have Bot Management enabled, Cloudflare will allow the deployment of firewall rules for bot mitigation purposes to your zone. You may disable or remove any of these firewall rules from your zone at any time by going to the firewall tab of your Cloudflare account.</p>
			<p>Firewall rules applied to your zone count towards your total allotment of firewall rules. You may see audit log events when firewall rules for bot mitigation are deployed to your zone.</p>
		</div>
	</div>
</section>
