<section
	class="cloudflare firewall user_agent_blocking initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="firewall"
	data-section-name="user_agent_blocking"
	data-item-count="0"
	data-page="1"
	data-page-size="15" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >User Agent Blocking</span>
			<p>
				Create a rule to block or challenge a specific User Agent from accessing your zone.
				</br></br>
				<strong class="usage" >You have 0 of 10 User Agent Blocking rules active</strong>
			</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<input type="button" class="trigger" data-target="create" value="Create Blocking Rule" />
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row" >
		<table cellpadding="0" cellspacing="0" >
			<thead>
				<tr>
					<th>Rule Name/Description</th>
					<th>Action</th>
				</tr>
			<thead>
			<tbody>
				<tr>
					<td colspan="2" >You currently have no User Agent Blocking rules. Please click on 'Create Blocking Rule' to get started.</td>
				</tr>
			</tbody>
		</table>
		<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<div class="pagination_container" >
				<span class="previous trigger" data-target="previous_page" >&#xF002;</span>
				<div class="pages" ></div>
				<span class="next trigger" data-target="next_page" >&#xF003;</span>
				<span class="showing" >0 - 0 of 0 records</span>
			</div>
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<p>User-Agent Blocking allows you to block a specific (complete) User-Agent string, and provides you with options as to how block/mitigate it. The list of actions permitted are the same as the IP Firewall, those being Block, JS Challenge, Captcha and Challenge.</p>
			<p>This is best used in a scenario where you are under attack from a specific User-Agent, or looking to block specific versions of a browser or web application, e.g. “curl/7.37.0”</p>
		</div>
	</div>
</section>
