<section
	class="cloudflare caching browser_cache_expiration initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="caching"
	data-section-name="browser_cache_expiration" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Browser Cache TTL</span>
			<p>Determine the length of time Cloudflare instructs a visitor’s browser to cache files. During this period, the browser loads the files from its local cache, speeding up page loads.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<select class="trigger-select" name="value" data-target="update" >
					<option value="0" >Respect Existing Headers</option>
					<option value="1800" >30 minutes</option>
					<option value="3600" >1 hour</option>
					<option value="7200" >2 hours</option>
					<option value="10800" >3 hours</option>
					<option value="14400" >4 hours</option>
					<option value="18000" >5 hours</option>
					<option value="28800" >8 hours</option>
					<option value="43200" >12 hours</option>
					<option value="57600" >16 hours</option>
					<option value="72000" >20 hours</option>
					<option value="86400" >1 day</option>
					<option value="172800" >2 days</option>
					<option value="259200" >3 days</option>
					<option value="345600" >4 days</option>
					<option value="432000" >5 days</option>
					<option value="691200" >8 days</option>
					<option value="1382400" >16 days</option>
					<option value="2073600" >24 days</option>
					<option value="2678400" >1 month</option>
					<option value="5356800" >2 months</option>
					<option value="16070400" >6 months</option>
					<option value="31536000" >1 year</option>
				</select>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What does the Browser Cache Expiration do?</h4>
			<p>The Browser Cache Expiration specifies how long cached files will remain in your visitor’s browser cache. This expiration time is what Cloudflare will set unless longer time periods are specified at your web server.</p>
			<p>A longer expiration time ensures faster load times for repeat visitors. However, a longer expiration time also means slower update times if those files are modified.</p>
			<p>To learn more about Browser Cache Expiration see <a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168366-What-does-browser-cache-expire-TTL-mean" >here</a>.</p>
			<p><strong>Note:</strong> You can also increase the cache expiration by specifying a longer cache time on the origin server, or you can set a different Cache Expiration for a specific path or resource using the Page Rules app. Cloudflare will use whichever value is longer between your origin server cache headers and your Cloudflare setting</p>
			<br>
			<h5 id="additional-resources">Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168276-What-does-the-Browser-Cache-Expiration-do" >What does the Browser Cache Expiration do?</a>
		</div>
	</div>
</section>
