<section
	class="cloudflare caching development_mode initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="caching"
	data-section-name="development_mode" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Development Mode</span>
			<p>Temporarily bypass our cache allowing you to see changes to your origin server in realtime.</p>
			<p><b>Note:</b> Enabling this feature can significantly increase origin server load. Development mode does not purge the cache so files will need to be purged after development mode expires.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" > </div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What does Development Mode do?</h4>
			<p>When Development Mode is on, all requests will be passed to the origin server. This allows requests for your website to temporarily bypass our cache so you can verify changes made to cached content.</p>
			<p>This is useful if you need to see changes immediately. Once enabled, Development Mode lasts for three hours and then automatically turns off.</p>
			<p><strong>Note:</strong> Unless you are making major changes to your website, we recommend using the Purge Individual Files option instead of turning on Development Mode. This is because Development Mode will cause all requests to go to your origin server, and increased requests to your origin server will temporarily raise your bandwidth and CPU usage.</p>
			<br>
			<h5>Additional Resources</h5>
			<a target="blank" href="https://support.cloudflare.com/hc/en-us/articles/200168246-What-does-Cloudflare-Development-mode-mean">What does Cloudflare Development mode mean?</a>
		</div>
	</div>
</section>
