<script>
	window.domain = "<?php echo $block->getDomainName () ?>"
	window.skin_base = "<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/') ?>"
	window.form_key = "<?php echo $block->getFormKey () ?>"
</script>

<div class="cloudflare-dashboard" >
	<div class="dashboard-header" >
		<div class="logo" >
			<img src="<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/jetrails.svg') ?>" />
		</div>
		<div class="domain_wrapper" >
			<div class="selected" ><?php echo $block->getDomainName () ?></div>
			<div class="options" >
				<?php foreach ( $block->getDomainNames () as $domain ): ?>
					<?php if ( $domain ["active"] ): ?>
						<a>
							<div class="option active" >
								<?php echo $domain ["name"] ?>
							</div>
						</a>
					<?php else: ?>
						<a href="<?php echo $domain ["action"] ?>" >
							<div class="option" >
								<?php echo $domain ["name"] ?>
							</div>
						</a>
					<?php endif ?>
				<?php endforeach ?>
			</div>
		</div>
		<div class="attribution" ></div>
	</div>
	<div class="dashboard-main" >
		<ul class="tabs" >
			<li data-tab="overview" class="selected" >
				<span>&#xF00A;</span>
				<span>Overview</span>
			</li>
			<?php if ( $block->isValidAuth () && $block->isValidZone () ): ?>
				<li data-tab="dns" >
					<span>&#xF00F;</span><span>DNS</span>
				</li>
				<li data-tab="ssl_tls" >
					<span>&#xF011;</span><span>SSL/TLS</span>
				</li>
				<li data-tab="firewall" >
					<span>&#xF014;</span><span>Firewall</span>
				</li>
				<li data-tab="speed" >
					<span>&#xF00B;</span><span>Speed</span>
				</li>
				<li data-tab="caching" >
					<span>&#xF00D;</span><span>Caching</span>
				</li>
				<li data-tab="page_rules" >
					<span>&#xF00E;</span><span>Page Rules</span>
				</li>
				<li data-tab="network" >
					<span>&#xE905;</span><span>Network</span>
				</li>
				<li data-tab="scrape_shield" >
					<span>&#xF013;</span><span>Scrape Shield</span>
				</li>
			<?php endif ?>
			<li data-tab="hosting" >
				<svg viewBox="100 100 300 300"><g fill="#FFF"><path d="M102 209.2v-15.7a2 2 0 012.8-2L205.5 240c.8.4 1.2 1 1.2 2v17.5c0 .8-.4 1.4-1.2 1.8l-100.7 48.4a2 2 0 01-2.8-1.8V292c0-.8.4-1.4 1.2-1.8l79.4-37.6a2 2 0 000-3.6l-79.4-38a2 2 0 01-1.2-2.1v.2zM255 311v-98.6c0-1.2-.8-2-2-2H229a2 2 0 01-2-2v-16.1c0-1.2.8-2 2-2h44.3c1.2 0 2 .8 2 2V311a40.4 40.4 0 01-40.3 40.2h-26.2a2 2 0 01-2-2v-16c0-1.3.8-2 2-2H235c11.1 0 20.1-9.1 20.1-20.2zm0-161h18.2c1.2 0 2 .8 2 2v16.1c0 1.2-.8 2-2 2H255a2 2 0 01-2-2v-16c0-1.3.8-2.1 2-2.1zM400 293v16c0 1.3-.8 2-2 2H297.3a2 2 0 01-2-2v-16c0-1.3.8-2 2-2H398c1.2 0 2 .7 2 2z"></path></g></svg>
				<span>Magento Hosting</span>
			</li>
		</ul>
		<div class="content-wrapper" >
			<div class="content" data-target="hosting" >
				<?php echo $block->getTabContent ("hosting") ?>
			</div>
			<div class="content" data-target="overview" >
				<?php echo $block->getTabContent ("overview") ?>
			</div>
			<?php if ( $block->isValidAuth () && $block->isValidZone () ): ?>
				<div class="content" data-target="dns" >
					<?php echo $block->getTabContent ("dns") ?>
				</div>
				<div class="content" data-target="ssl_tls" >
					<?php echo $block->getTabContent ("ssl_tls") ?>
				</div>
				<div class="content" data-target="firewall" >
					<?php echo $block->getTabContent ("firewall") ?>
				</div>
				<div class="content" data-target="speed" >
					<?php echo $block->getTabContent ("speed") ?>
				</div>
				<div class="content" data-target="caching" >
					<?php echo $block->getTabContent ("caching") ?>
				</div>
				<div class="content" data-target="page_rules" >
					<?php echo $block->getTabContent ("page_rules") ?>
				</div>
				<div class="content" data-target="network" >
					<?php echo $block->getTabContent ("network") ?>
				</div>
				<div class="content" data-target="scrape_shield" >
					<?php echo $block->getTabContent ("scrape_shield") ?>
				</div>
			<?php endif ?>
		</div>
	</div>
	<div class="overlay" ></div>
</div>
