<section class='tabs-wrapper at_least_one' >
	<div data-tab='waf' class="active" >WAF</div>
	<div data-tab='tools' >Tools</div>
	<div data-tab='settings' >Settings</div>
	<div data-tab-content='waf' class='active' >
		<?php

			echo $block->renderSections ( "firewall/waf", array (
				"web_application_firewall",
				"firewall_rules"
			));

		?>
	</div>
	<div data-tab-content='tools' >
		<?php

			echo $block->renderSections ( "firewall/tools_tab", array (
				"access_rules",
				"user_agent_blocking",
				"unmetered_ddos_mitigation",
				"zone_lockdown"
			));

		?>
	</div>
	<div data-tab-content='settings' >
		<?php

			echo $block->renderSections ( "firewall/settings_tab", array (
				"security_level",
				"bot_fight_mode",
				"bot_management",
				"javascript_detections",
				"challenge_passage",
				"browser_integrity_check",
				"privacy_pass_support"
			));

		?>
	</div>
</section>
