<h1 class="tab-content" >Network</h1>
<h2 class="tab-content" >Manage network settings for your website</h2>
<?php

	echo $block->renderSections ( "network", array (
		"http_2",
		"http_2_to_origin",
		"http_3",
		"zero_rtt_connection_resumption",
		"ipv6_compatibility",
		"grpc",
		"websockets",
		"onion_routing",
		"pseudo_ipv4",
		"ip_geolocation",
		"maximum_upload_size",
		"response_buffering",
		"true_client_ip_header"
	));

?>
