<section
	class="cloudflare hosting cta-tom"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="hosting"
	data-section-name="cta-tom" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Schedule A Meeting With <u>Tom</u>!</span>
			<p>Discuss your Magento hosting challenges with an expert.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<input type="button" value="Schedule Meeting" onClick="window.open ('https://calendly.com/tom-p','_blank')" />
			</div>
		</div>
	</div>
</section>
