<section
	class="cloudflare hosting cta-tom"
	data-endpoint="<?php echo $block->escapeUrl ( $block->getApiEndpoint () ) ?>"
	data-form-key="<?php echo $block->escapeHtmlAttr ( $block->getFormKey () ) ?>"
	data-tab-name="hosting"
	data-section-name="cta-tom" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Get In Touch!</span>
			<p>Discuss your Magento hosting challenges with an expert.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<input type="button" value="Schedule Meeting" onClick="window.location = 'mailto:sales@jetrails.com'" />
			</div>
		</div>
	</div>
</section>
