<section
	class="cloudflare hosting main"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="hosting"
	data-section-name="main" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Ready For Better Magento Hosting?</span>
			<p>Did you know that JetRails can configure, optimize, monitor, and manage, your Cloudflare account, along with malware scanners, intrusion detection systems, off-server backups, caching layers, and more! It’s all part of JetRails mission-critical hosting services!</p>
			<center>
				<iframe width="95%" height="400" src="https://magento-cloudflare.jetrails.com" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
			</center>
		</div>
	</div>
</section>