<section
	class="cloudflare speed enhanced_http2_prioritization initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="enhanced_http2_prioritization" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Enhanced HTTP/2 Prioritization</span>
			<p>Optimizes the order of resource delivery, independent of the browser. Greatest improvements will be experienced by visitors using Safari and Edge browsers.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<label class="switch" >
					<input class="trigger" type="checkbox" name="mode" data-target="toggle" />
					<span class="knob" ></span>
				</label>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h3>What does Enhanced HTTP/2 Prioritization do?</h3>
			<p>The speed of loading web content, from the user's perspective, is dependent on the order in which the resources load. With HTTP/2, by default, Cloudflare will follow the order requested by the browser. This ordering varies from browser to browser, causing a significant difference in performance. </p>
			<p>With Enhanced HTTP/2 Prioritization enabled, resources will be  delivered in the optimal order for the fastest experience across all browsers. Read more about it on our <a href="https://blog.cloudflare.com/better-http-2-prioritization-for-a-faster-web" >blog post.</a></p>
		</div>
	</div>
</section>
