<section
	class="cloudflare speed mobile_redirect initialize loading"
	data-endpoint="<?php echo $block->getApiEndpoint () ?>"
	data-form-key="<?php echo $block->getFormKey () ?>"
	data-tab-name="speed"
	data-section-name="mobile_redirect" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="section_title" >Mobile Redirect</span>
			<p>Redirect visitors that are using mobile devices to a mobile-optimized website.</p>
		</div>
		<div class="wrapper_right" >
			<div>
				<div class="group_wrapper" style="max-width: 300px" >
					<select class="trigger-select" data-target="change" name="mobile_subdomain" ></select>
				</div>
				<div class="group_wrapper" style="max-width: 300px" >
					<select class="trigger-select" data-target="change" name="strip_uri" >
						<option value="false" >Keep Path</option>
						<option value="true" >Drop Path</option>
					</select>
				</div>
				<div class="group_wrapper" style="text-align:center" >
					<label class="switch" >
						<input class="trigger" type="checkbox" name="status" data-target="change" />
						<span class="knob" ></span>
					</label>
				</div>
			</div>
			<div class="lightbox" style="background-image: url(<?php echo $block->getViewFileUrl ('JetRails_Cloudflare/images/loading.svg') ?>)" ></div>
		</div>
	</div>
	<div class="row collapsable" >
		<div class="wrapper_bottom" >
			<a data-tab="help" >Help</a>
		</div>
		<div data-tab-content="help" >
			<h4>What does Mobile Redirect do?</h4>
			<p><a href="https://support.cloudflare.com/hc/articles/200168336" >Mobile Redirect automatically redirects</a> visitors using mobile devices to a website specifically for those devices.</p>
			<p>Cloudflare redirects visitors at the edge. This avoids a request to your origin server, directing visitors to your mobile-optimized website even faster.</p>
			<p>Cloudflare must be enabled on %{name} or www.%{name} to use Mobile redirect.</p>
			<h4>What Mobile Redirect setting should I use?</h4>
			<ul>
				<li>
					<strong>Drop path:</strong> Redirect all mobile requests to your mobile-optimized website homepage.
					<ul>
						<li>Example: <code>http://%{name}/page.html</code> → <code>http://mobile.%{name}</code></li>
					</ul>
				</li>
				<li>
					<strong>Keep path:</strong> Redirect all mobile requests to the same resource hosted on your mobile-optimized website.
					<ul>
						<li>Example: <code>http://%{name}/page.html</code> → <code>http://mobile.%{name}/page.html</code></li>
					</ul>
				</li>
			</ul>
		</div>
	</div>
</section>
