<section class="cloudflare restricted" >
	<div class="row" >
		<div class="wrapper_left" >
			<span class="cloudflare-font" >&#xF006;</span>
			<span class="section_title" >Restricted Area</span>
			<p>You currently do not have permission to view the contents of this tab.  If you would like to get access, contact your store administrator and ask them to give your role permission in the Magento ACL.</p>
		</div>
	</div>
</section>
